name: Power alerts

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: daily_sent.json
          key: power-daily-cache
          restore-keys: |
            power-daily-cache

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r scripts/light_outage/requirements.txt

      - run: python scripts/light_outage/power.py
        env:
          TG_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
          TG_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}