name: power alerts

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore state
        uses: actions/cache/restore@v3
        with:
          path: daily_sent.json
          key: outage-state-${{ github.run_number }}
          restore-keys: |
            outage-state-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install deps
        run: pip install -r scripts/light_outage/requirements.txt
      
      - name: Run script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python scripts/light_outage/power.py
        env:
      
      - name: Save state
        uses: actions/cache/save@v3
        if: always()
        with:
          path: daily_sent.json
          key: outage-state-${{ github.run_number }}